// Generated by gencpp from file wsg_50_common/Cmd.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_CMD_H
#define WSG_50_COMMON_MESSAGE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wsg_50_common
{
template <class ContainerAllocator>
struct Cmd_
{
  typedef Cmd_<ContainerAllocator> Type;

  Cmd_()
    : mode()
    , pos(0.0)
    , speed(0.0)  {
    }
  Cmd_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , pos(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef float _pos_type;
  _pos_type pos;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::wsg_50_common::Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wsg_50_common::Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Cmd_

typedef ::wsg_50_common::Cmd_<std::allocator<void> > Cmd;

typedef boost::shared_ptr< ::wsg_50_common::Cmd > CmdPtr;
typedef boost::shared_ptr< ::wsg_50_common::Cmd const> CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wsg_50_common::Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wsg_50_common::Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wsg_50_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wsg_50_common': ['/home/ravi/classic_ur_ws/src/wsg50-ros-pkg/wsg_50_common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::Cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::Cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wsg_50_common::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9d4654d92a2e086717420189f98c76a";
  }

  static const char* value(const ::wsg_50_common::Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9d4654d92a2e086ULL;
  static const uint64_t static_value2 = 0x717420189f98c76aULL;
};

template<class ContainerAllocator>
struct DataType< ::wsg_50_common::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wsg_50_common/Cmd";
  }

  static const char* value(const ::wsg_50_common::Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wsg_50_common::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n\
float32 pos\n\
float32 speed\n\
\n\
";
  }

  static const char* value(const ::wsg_50_common::Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wsg_50_common::Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wsg_50_common::Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wsg_50_common::Cmd_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "pos: ";
    Printer<float>::stream(s, indent + "  ", v.pos);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_CMD_H
