// Generated by gencpp from file wsg_50_common/ConfRequest.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_CONFREQUEST_H
#define WSG_50_COMMON_MESSAGE_CONFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wsg_50_common
{
template <class ContainerAllocator>
struct ConfRequest_
{
  typedef ConfRequest_<ContainerAllocator> Type;

  ConfRequest_()
    : val(0.0)  {
    }
  ConfRequest_(const ContainerAllocator& _alloc)
    : val(0.0)  {
  (void)_alloc;
    }



   typedef float _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::wsg_50_common::ConfRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wsg_50_common::ConfRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfRequest_

typedef ::wsg_50_common::ConfRequest_<std::allocator<void> > ConfRequest;

typedef boost::shared_ptr< ::wsg_50_common::ConfRequest > ConfRequestPtr;
typedef boost::shared_ptr< ::wsg_50_common::ConfRequest const> ConfRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wsg_50_common::ConfRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wsg_50_common::ConfRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wsg_50_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wsg_50_common': ['/home/ravi/classic_ur_ws/src/wsg50-ros-pkg/wsg_50_common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::ConfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::ConfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::ConfRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ee899b5f0899afa6060c9ba611652c";
  }

  static const char* value(const ::wsg_50_common::ConfRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ee899b5f0899afULL;
  static const uint64_t static_value2 = 0xa6060c9ba611652cULL;
};

template<class ContainerAllocator>
struct DataType< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wsg_50_common/ConfRequest";
  }

  static const char* value(const ::wsg_50_common::ConfRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 val\n\
";
  }

  static const char* value(const ::wsg_50_common::ConfRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wsg_50_common::ConfRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wsg_50_common::ConfRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<float>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_CONFREQUEST_H
