// Generated by gencpp from file wsg_50_common/Conf.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_CONF_H
#define WSG_50_COMMON_MESSAGE_CONF_H

#include <ros/service_traits.h>


#include <wsg_50_common/ConfRequest.h>
#include <wsg_50_common/ConfResponse.h>


namespace wsg_50_common
{

struct Conf
{

typedef ConfRequest Request;
typedef ConfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Conf
} // namespace wsg_50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wsg_50_common::Conf > {
  static const char* value()
  {
    return "0c7a1839200830facdc1205cf36615d5";
  }

  static const char* value(const ::wsg_50_common::Conf&) { return value(); }
};

template<>
struct DataType< ::wsg_50_common::Conf > {
  static const char* value()
  {
    return "wsg_50_common/Conf";
  }

  static const char* value(const ::wsg_50_common::Conf&) { return value(); }
};


// service_traits::MD5Sum< ::wsg_50_common::ConfRequest> should match 
// service_traits::MD5Sum< ::wsg_50_common::Conf > 
template<>
struct MD5Sum< ::wsg_50_common::ConfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::ConfRequest> should match 
// service_traits::DataType< ::wsg_50_common::Conf > 
template<>
struct DataType< ::wsg_50_common::ConfRequest>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wsg_50_common::ConfResponse> should match 
// service_traits::MD5Sum< ::wsg_50_common::Conf > 
template<>
struct MD5Sum< ::wsg_50_common::ConfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::ConfResponse> should match 
// service_traits::DataType< ::wsg_50_common::Conf > 
template<>
struct DataType< ::wsg_50_common::ConfResponse>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_CONF_H
