// Generated by gencpp from file wsg_50_common/Incr.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_INCR_H
#define WSG_50_COMMON_MESSAGE_INCR_H

#include <ros/service_traits.h>


#include <wsg_50_common/IncrRequest.h>
#include <wsg_50_common/IncrResponse.h>


namespace wsg_50_common
{

struct Incr
{

typedef IncrRequest Request;
typedef IncrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Incr
} // namespace wsg_50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wsg_50_common::Incr > {
  static const char* value()
  {
    return "b996830260cb95e784a9d9fbb5e34c61";
  }

  static const char* value(const ::wsg_50_common::Incr&) { return value(); }
};

template<>
struct DataType< ::wsg_50_common::Incr > {
  static const char* value()
  {
    return "wsg_50_common/Incr";
  }

  static const char* value(const ::wsg_50_common::Incr&) { return value(); }
};


// service_traits::MD5Sum< ::wsg_50_common::IncrRequest> should match 
// service_traits::MD5Sum< ::wsg_50_common::Incr > 
template<>
struct MD5Sum< ::wsg_50_common::IncrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Incr >::value();
  }
  static const char* value(const ::wsg_50_common::IncrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::IncrRequest> should match 
// service_traits::DataType< ::wsg_50_common::Incr > 
template<>
struct DataType< ::wsg_50_common::IncrRequest>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Incr >::value();
  }
  static const char* value(const ::wsg_50_common::IncrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wsg_50_common::IncrResponse> should match 
// service_traits::MD5Sum< ::wsg_50_common::Incr > 
template<>
struct MD5Sum< ::wsg_50_common::IncrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Incr >::value();
  }
  static const char* value(const ::wsg_50_common::IncrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::IncrResponse> should match 
// service_traits::DataType< ::wsg_50_common::Incr > 
template<>
struct DataType< ::wsg_50_common::IncrResponse>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Incr >::value();
  }
  static const char* value(const ::wsg_50_common::IncrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_INCR_H
