// Generated by gencpp from file wsg_50_common/MoveRequest.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_MOVEREQUEST_H
#define WSG_50_COMMON_MESSAGE_MOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wsg_50_common
{
template <class ContainerAllocator>
struct MoveRequest_
{
  typedef MoveRequest_<ContainerAllocator> Type;

  MoveRequest_()
    : width(0.0)
    , speed(0.0)  {
    }
  MoveRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::wsg_50_common::MoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wsg_50_common::MoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRequest_

typedef ::wsg_50_common::MoveRequest_<std::allocator<void> > MoveRequest;

typedef boost::shared_ptr< ::wsg_50_common::MoveRequest > MoveRequestPtr;
typedef boost::shared_ptr< ::wsg_50_common::MoveRequest const> MoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wsg_50_common::MoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wsg_50_common::MoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wsg_50_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wsg_50_common': ['/home/ravi/classic_ur_ws/src/wsg50-ros-pkg/wsg_50_common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wsg_50_common::MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wsg_50_common::MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wsg_50_common::MoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2d4f46fe020a06d64128c90310c767d";
  }

  static const char* value(const ::wsg_50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2d4f46fe020a06dULL;
  static const uint64_t static_value2 = 0x64128c90310c767dULL;
};

template<class ContainerAllocator>
struct DataType< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wsg_50_common/MoveRequest";
  }

  static const char* value(const ::wsg_50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n\
float32 speed\n\
";
  }

  static const char* value(const ::wsg_50_common::MoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wsg_50_common::MoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wsg_50_common::MoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_MOVEREQUEST_H
