// Generated by gencpp from file wsg_50_common/Move.msg
// DO NOT EDIT!


#ifndef WSG_50_COMMON_MESSAGE_MOVE_H
#define WSG_50_COMMON_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <wsg_50_common/MoveRequest.h>
#include <wsg_50_common/MoveResponse.h>


namespace wsg_50_common
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace wsg_50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wsg_50_common::Move > {
  static const char* value()
  {
    return "ac4bc9278b95c49c6bb95b3db7e0a0e4";
  }

  static const char* value(const ::wsg_50_common::Move&) { return value(); }
};

template<>
struct DataType< ::wsg_50_common::Move > {
  static const char* value()
  {
    return "wsg_50_common/Move";
  }

  static const char* value(const ::wsg_50_common::Move&) { return value(); }
};


// service_traits::MD5Sum< ::wsg_50_common::MoveRequest> should match 
// service_traits::MD5Sum< ::wsg_50_common::Move > 
template<>
struct MD5Sum< ::wsg_50_common::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Move >::value();
  }
  static const char* value(const ::wsg_50_common::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::MoveRequest> should match 
// service_traits::DataType< ::wsg_50_common::Move > 
template<>
struct DataType< ::wsg_50_common::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Move >::value();
  }
  static const char* value(const ::wsg_50_common::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wsg_50_common::MoveResponse> should match 
// service_traits::MD5Sum< ::wsg_50_common::Move > 
template<>
struct MD5Sum< ::wsg_50_common::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Move >::value();
  }
  static const char* value(const ::wsg_50_common::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::MoveResponse> should match 
// service_traits::DataType< ::wsg_50_common::Move > 
template<>
struct DataType< ::wsg_50_common::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Move >::value();
  }
  static const char* value(const ::wsg_50_common::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_MOVE_H
